[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run db:migrate && npm start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
